version: "3.9"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    user: "postgres"
    environment:
      POSTGRES_DB: "demo"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"

  app:
    image: app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/app
    ports:
      - "4567:4567"
    depends_on:
      - "elastic"
      - "db"
    command: bundle exec rackup -p 4567 -o 0.0.0.0
    restart: on-failure

  web:
    image: web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - "app"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    container_name: elastic
    environment:
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
