require 'sequel'
require 'faker'

task :seed do
  DATABASE_URL = ENV.fetch(
    'DATABASE_URL',
    'postgresql://user:pass@db:5432/demo'
  )

  DB = Sequel.connect(DATABASE_URL)

  DB.create_table :posts do
    String :title
    String :text
  end

  1000.times do
    DB[:posts].insert(
      title: Faker::Lorem.sentence,
      text: Faker::Lorem.paragraph
    )
  end
end

